// Euphoria - Copyright (c) Gustav

#ifndef BUILD_EUPHORIA_CONFIG_H_
#define BUILD_EUPHORIA_CONFIG_H_

/** @file
Configuration related configurations generated by cmake from euphoria-config-in.h
 */

// header for cmake to generate for euphoria 
#cmakedefine USE_TWEAKABLES

#endif  // BUILD_EUPHORIA_CONFIG_H_
