// Euphoria - Copyright (c) Gustav

#ifndef BUILD_EUPHORIA_CONFIG_H_
#define BUILD_EUPHORIA_CONFIG_H_

/** @file
Configuration related configurations generated by cmake from euphoria-config-in.h
 */

// header for cmake to generate for euphoria
#cmakedefine USE_TWEAKABLES
#cmakedefine USE_OCULUS
#cmakedefine EUPHORIA_MESA_COMPABILITY

#endif  // BUILD_EUPHORIA_CONFIG_H_
